plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    alias(libs.plugins.kotlin.compose.compiler)
}

android {
    namespace 'com.example.ui_common'
    compileSdkVersion AndroidConfig.COMPILE_SDK_VERSION

    defaultConfig {
        minSdkVersion AndroidConfig.MIN_SDK_VERSION
        targetSdkVersion AndroidConfig.TARGET_SDK_VERSION

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = KotlinOptions.JVM_TARGET
    }
    buildFeatures {
        compose true
    }

}

dependencies {

    //core
    api core.appcompat
    api core.ktx
    api core.material

    //compose
    def composeBom = platform(libs.compose.bom)
    implementation composeBom

    api(libs.bundles.compose.core)
    api(libs.compose.constraintlayout)
    api(libs.compose.navigation)

    // 4. Tooling
    debugImplementation libs.compose.ui.tooling

    //other
    implementation(other.coil)


    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}